server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  kafka:
    admin:
      security:
        protocol:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 683654054004-gsofq4ovjs32f7ehunqllnskto306njl.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

